openapi: 3.0.0
info:
  title: Sign.plus Developer API v2
  description: Integrate legally-binding electronic signature to your workflow
  version: 2.0.0
  contact:
    name: Sign.Plus
    url: https://sign.plus
    email: support@alohi.com
servers:
  - url: https://restapi.sign.plus/v2
    description: Sign.Plus API - Production
tags:
  - name: signplus
    description: Sign.plus API
paths:
  /envelope:
    post:
      description: Create new envelope
      operationId: create_envelope
      tags:
        - signplus
      security:
        - BearerAuth:
            - SIGN_ALL_EDIT
  "/envelope/from_template/{template_id}":
    post:
      description: Create new envelope from template
      operationId: create_envelope_from_template
      tags:
        - signplus
      security:
        - BearerAuth:
            - SIGN_ALL_EDIT
  /envelopes:
    post:
      description: List envelopes
      operationId: list_envelopes
      tags:
        - signplus
      security:
        - BearerAuth:
            - SIGN_ALL_READ
  "/envelope/{envelope_id}":
    get:
      description: Get envelope
      operationId: get_envelope
      tags:
        - signplus
      security:
        - BearerAuth:
            - SIGN_ALL_READ
    delete:
      description: Delete envelope
      operationId: delete_envelope
      tags:
        - signplus
      security:
        - BearerAuth:
            - SIGN_ALL_EDIT
  "/envelope/{envelope_id}/document/{document_id}":
    get:
      description: Get envelope document
      operationId: get_envelope_document
      tags:
        - signplus
      security:
        - BearerAuth:
            - SIGN_ALL_READ
  "/envelope/{envelope_id}/documents":
    get:
      description: Get envelope documents
      operationId: get_envelope_documents
      tags:
        - signplus
      security:
        - BearerAuth:
            - SIGN_ALL_READ
  "/envelope/{envelope_id}/document":
    post:
      description: Add envelope document
      operationId: add_envelope_document
      tags:
        - signplus
      security:
        - BearerAuth:
            - SIGN_ALL_EDIT
  "/envelope/{envelope_id}/dynamic_fields":
    put:
      description: Set envelope dynamic fields
      operationId: set_envelope_dynamic_fields
      tags:
        - signplus
      security:
        - BearerAuth:
            - SIGN_ALL_EDIT
  "/envelope/{envelope_id}/signing_steps":
    post:
      description: Add envelope signing steps
      operationId: add_envelope_signing_steps
      tags:
        - signplus
      security:
        - BearerAuth:
            - SIGN_ALL_EDIT
  "/envelope/{envelope_id}/send":
    post:
      description: Send envelope for signature
      operationId: send_envelope
      tags:
        - signplus
      security:
        - BearerAuth:
            - SIGN_ALL_EDIT
  "/envelope/{envelope_id}/duplicate":
    post:
      description: Duplicate envelope
      operationId: duplicate_envelope
      tags:
        - signplus
      security:
        - BearerAuth:
            - SIGN_ALL_EDIT
  "/envelope/{envelope_id}/void":
    put:
      description: Void envelope
      operationId: void_envelope
      tags:
        - signplus
      security:
        - BearerAuth:
            - SIGN_ALL_EDIT
  "/envelope/{envelope_id}/rename":
    put:
      description: Rename envelope
      operationId: rename_envelope
      tags:
        - signplus
      security:
        - BearerAuth:
            - SIGN_ALL_EDIT
  "/envelope/{envelope_id}/set_comment":
    put:
      description: Set envelope comment
      operationId: set_envelope_comment
      tags:
        - signplus
      security:
        - BearerAuth:
            - SIGN_ALL_EDIT
  "/envelope/{envelope_id}/set_notification":
    put:
      description: Set envelope notification
      operationId: set_envelope_notification
      tags:
        - signplus
      security:
        - BearerAuth:
            - SIGN_ALL_EDIT
  "/envelope/{envelope_id}/set_expiration_date":
    put:
      description: Set envelope expiration date
      operationId: set_envelope_expiration_date
      tags:
        - signplus
      security:
        - BearerAuth:
            - SIGN_ALL_EDIT
  "/envelope/{envelope_id}/set_legality_level":
    put:
      description: Set envelope legality level
      operationId: set_envelope_legality_level
      tags:
        - signplus
      security:
        - BearerAuth:
            - SIGN_ALL_EDIT
  "/envelope/{envelope_id}/annotations":
    get:
      description: Get envelope annotations
      operationId: get_envelope_annotations
      tags:
        - signplus
      security:
        - BearerAuth:
            - SIGN_ALL_EDIT
  "/envelope/{envelope_id}/annotations/{document_id}":
    get:
      description: Get envelope document annotations
      operationId: get_envelope_document_annotations
      tags:
        - signplus
      security:
        - BearerAuth:
            - SIGN_ALL_EDIT
  "/envelope/{envelope_id}/annotation":
    post:
      description: Add envelope annotation
      operationId: add_envelope_annotation
      tags:
        - signplus
      security:
        - BearerAuth:
            - SIGN_ALL_EDIT
  "/envelope/{envelope_id}/annotation/{annotation_id}":
    delete:
      description: Delete envelope annotation
      operationId: delete_envelope_annotation
      tags:
        - signplus
      security:
        - BearerAuth:
            - SIGN_ALL_EDIT
  /template:
    post:
      description: Create new template
      operationId: create_template
      tags:
        - signplus
      security:
        - BearerAuth:
            - SIGN_ALL_EDIT
  /templates:
    post:
      description: List templates
      operationId: list_templates
      tags:
        - signplus
      security:
        - BearerAuth:
            - SIGN_ALL_READ
  "/template/{template_id}":
    get:
      description: Get template
      operationId: get_template
      tags:
        - signplus
      security:
        - BearerAuth:
            - SIGN_ALL_READ
    delete:
      description: Delete template
      operationId: delete_template
      tags:
        - signplus
      security:
        - BearerAuth:
            - SIGN_ALL_EDIT
  "/template/{template_id}/duplicate":
    post:
      description: Duplicate template
      operationId: duplicate_template
      tags:
        - signplus
      security:
        - BearerAuth:
            - SIGN_ALL_EDIT
  "/template/{template_id}/document":
    post:
      description: Add template document
      operationId: add_template_document
      tags:
        - signplus
      security:
        - BearerAuth:
            - SIGN_ALL_EDIT
  "/template/{template_id}/document/{document_id}":
    get:
      description: Get template document
      operationId: get_template_document
      tags:
        - signplus
      security:
        - BearerAuth:
            - SIGN_ALL_READ
  "/template/{template_id}/documents":
    get:
      description: Get template documents
      operationId: get_template_documents
      tags:
        - signplus
      security:
        - BearerAuth:
            - SIGN_ALL_READ
  "/template/{template_id}/signing_steps":
    post:
      description: Add template signing steps
      operationId: add_template_signing_steps
      tags:
        - signplus
      security:
        - BearerAuth:
            - SIGN_ALL_EDIT
  "/template/{template_id}/rename":
    put:
      description: Rename template
      operationId: rename_template
      tags:
        - signplus
      security:
        - BearerAuth:
            - SIGN_ALL_EDIT
  "/template/{template_id}/set_comment":
    put:
      description: Set template comment
      operationId: set_template_comment
      tags:
        - signplus
      security:
        - BearerAuth:
            - SIGN_ALL_EDIT
  "/template/{template_id}/set_notification":
    put:
      description: Set template notification
      operationId: set_template_notification
      tags:
        - signplus
      security:
        - BearerAuth:
            - SIGN_ALL_EDIT
  "/template/{template_id}/annotations":
    get:
      description: Get template annotations
      operationId: get_template_annotations
      tags:
        - signplus
      security:
        - BearerAuth:
            - SIGN_ALL_EDIT
  "/template/{template_id}/annotations/{document_id}":
    get:
      description: Get document template annotations
      operationId: get_document_template_annotations
      tags:
        - signplus
      security:
        - BearerAuth:
            - SIGN_ALL_EDIT
  "/template/{template_id}/annotation":
    post:
      description: Add template annotation
      operationId: add_template_annotation
      tags:
        - signplus
      security:
        - BearerAuth:
            - SIGN_ALL_EDIT
  "/template/{template_id}/annotation/{annotation_id}":
    delete:
      description: Delete template annotation
      operationId: delete_template_annotation
      tags:
        - signplus
      security:
        - BearerAuth:
            - SIGN_ALL_EDIT
  /webhook:
    post:
      description: Create webhook
      operationId: create_webhook
      tags:
        - signplus
      security:
        - BearerAuth:
            - SIGN_ALL_EDIT
  /webhooks:
    post:
      description: List webhooks
      operationId: list_webhooks
      tags:
        - signplus
      security:
        - BearerAuth:
            - SIGN_ALL_READ
  "/webhook/{webhook_id}":
    delete:
      description: Delete webhook
      operationId: delete_webhook
      tags:
        - signplus
      security:
        - BearerAuth:
            - SIGN_ALL_EDIT
components:
  securitySchemes:
    BearerAuth:
      type: apiKey
      in: header
      name: Authorization